Mkw hiv mort
mrc-ide/frogger pull request #26
Opened 2023-07-27 11:49 UTC by mwalte10

- Integrated the HIV natural history bit for children off treatment
- changed all instances of hC to hc per jeff's comment in leapfrog check in on 25/7
- made all paed model functions have 'child' as the second word to indicate that they are paediatric functions
- removed all instances of hard coding related to age
- separated hc1 from hc2 for output of the hiv stratified population

2023-08-01 09:03 UTC, jeffeaton requested changes
This looks good. Adding a couple of small comments.

Please merge #11 into this branch and then re-review.

2023-08-02 09:32 UTC, mwalte10 commented on inst/include/child_model_simulation.hpp
> +        for (int cat = 0 ; cat < ss.hTM; ++cat) {
changing to hcTT for children Transmission Types

2023-08-02 10:22 UTC, mwalte10 commented on inst/include/child_model_simulation.hpp
> +        state_next.infections(af, g) = cpars.hc_nosocomial(time_step) / (5.0 * ss.num_genders);
updated

2023-08-15 16:03 UTC, mwalte10 commented
@r-ash here is the problem with the intermediate data

2023-08-17 15:45 UTC, r-ash commented
Not sure about the code factor issues here, it is complaining about empty lines but is seemingly referencing an old commit. Those blank lines have been removed.

2023-08-17 15:55 UTC, r-ash commented on src/model_setup.h
> +  const double ctx_effect = parse_data<double>(data, "ctx_effect", 1)(0);  // select the first element of a TensorMap1 and assign to double
Added support into the code generation to manage this.

2023-08-17 15:55 UTC, r-ash commented on inst/include/child_model_simulation.hpp
> +        for (int cat = 0; cat < hc_ss.hcTT; ++cat) {
Loop order here should be NS, hc1AG, hcTT, hc1DS

2023-08-18 14:38 UTC, r-ash approved these changes
This looks good to me, there are a few bits of commented out code which I would be tempted to remove if they're not needed anymore, or add a comment about why they are commented out.

2023-08-18 14:41 UTC, merged